version: '3.8'
services:
  app:
    container_name: react-typescript-styled-components-template
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.develop
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules/
    tty: true
